<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<!-- Можно включить Nullable и ImplicitUsings, но не обязательно -->
		<!--
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    -->
	</PropertyGroup>

	<ItemGroup>
		<!-- EF Core + SQLite -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0" />

		<!-- Identity с EF Core -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.0" />
	</ItemGroup>
</Project>
